const express=require('express');const http=require('http');const path=require('path');const Database=require('better-sqlite3');const jwt=require('jsonwebtoken');const {WebSocketServer}=require('ws');
const PORT=process.env.PORT||3000, JWT_SECRET=process.env.JWT_SECRET||'change-this-secret', ACCESS_CODE=process.env.CAMPEONE_CODE||'CAMPEONE', ADMIN_CODE=process.env.CAMPEONE_ADMIN_CODE||'CAMPEONE-ADMIN-2026';
const db=new Database(process.env.DB_PATH||path.join(__dirname,'campeone.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS state(id INTEGER PRIMARY KEY CHECK(id=1), data TEXT NOT NULL, updated_at TEXT NOT NULL)`);
const defaults={rules:{trainGoals:8,trainAssists:8,trainBonus:1,minMvpApps:3},schools:['Καλών Τεχνών','Ακαδημία','Πολυτεχνείο'],players:[...Array(12)].map((_,i)=>({id:i+1,name:['COOL','NOBEL','MUDI','MINI','BONE','MASTRO','LENKO','GEORGE','PLAYER9','PLAYER10','PLAYER11','PLAYER12'][i],school:['Καλών Τεχνών','Ακαδημία','Πολυτεχνείο'][i%3],schoolHistory:[]})),matches:[],meta:{version:1}};
if(!db.prepare('SELECT 1 FROM state WHERE id=1').get()) db.prepare('INSERT INTO state VALUES(1,?,?)').run(JSON.stringify(defaults),new Date().toISOString());
const getState=()=>JSON.parse(db.prepare('SELECT data FROM state WHERE id=1').get().data);const setState=s=>{s.meta={...(s.meta||{}),version:((s.meta?.version||0)+1)};db.prepare('UPDATE state SET data=?,updated_at=? WHERE id=1').run(JSON.stringify(s),new Date().toISOString());broadcast({type:'state',state:s});return s};
const app=express();app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));
function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace(/^Bearer /,''),JWT_SECRET);next()}catch{return res.status(401).json({error:'Μη έγκυρη σύνδεση'})}}
app.post('/api/login',(req,res)=>{const {code,name}=req.body||{};const role=code===ADMIN_CODE?'admin':(code===ACCESS_CODE?'player':null);if(!role)return res.status(403).json({error:'Λάθος κωδικός πρόσβασης'});const token=jwt.sign({name:name||'Παίκτης',role},JWT_SECRET,{expiresIn:'30d'});res.json({token,user:{name:name||'Παίκτης',role}})});
app.get('/api/state',auth,(req,res)=>res.json(getState()));
app.put('/api/state',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Μόνο admin μπορεί να αλλάξει δεδομένα'});const s=req.body;if(!s||!Array.isArray(s.players)||!Array.isArray(s.matches))return res.status(400).json({error:'Μη έγκυρα δεδομένα'});res.json(setState(s))});
app.post('/api/reset',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Μόνο admin'});res.json(setState(structuredClone(defaults)))});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const server=http.createServer(app),wss=new WebSocketServer({server});const clients=new Set();wss.on('connection',ws=>{clients.add(ws);ws.on('close',()=>clients.delete(ws));ws.send(JSON.stringify({type:'state',state:getState()}))});function broadcast(x){const m=JSON.stringify(x);for(const ws of clients)if(ws.readyState===1)ws.send(m)}server.listen(PORT,()=>console.log(`CAMPEONE running on http://localhost:${PORT}`));
